### ISSUE TITLE
How to ignore '@property(nonatomic, assign) NSInteger<OSIgnoreAttribute> priority;'

### ISSUE THREAD

**Issue by poholo** [expensivegasprices/BZObjectStore#15]
How to ignore '@property(nonatomic, assign) NSInteger<OSIgnoreAttribute> priority;'

using '@property(nonatomic, assign) NSNumber<OSIgnoreAttribute> * priority;'

**Comment by expensivegasprices** [comment]
Hi, poholo

Can you override attributeIsOSIgnoreAttribute method on your model?

Example
```
+ (BOOL)attributeIsOSIgnoreAttribute:(NSString*)attributeName
{
    if ([attributeName isEqualToString:@"xxx"]) {
        return YES;
    }
    return NO;
}
```
