### ISSUE TITLE
maybe BZJSON？

### ISSUE THREAD

**Issue by zeasy** [expensivegasprices/BZObjectStore#9]
maybe you can create a new JSON Model project..

"Any super class not required in your model"

:~)

**Comment by expensivegasprices** [comment]
Do you mean that BZObjectStore can be used with JSONModel library?
https://github.com/icanzilb/JSONModel

Yes, it can. Sample code with JSONModel is here.
https://github.com/expensivegasprices/BZObjectStore/tree/master/Samples/MarkdownAnywhere

**Comment by zeasy** [comment]
No，I wan't a project like JSONModel，but not required super class

**Comment by expensivegasprices** [comment]
BZObjectStore dose not plan having this function.
I recommend that you custom JSONModel.
